# Generated by Django 5.2.5 on 2026-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_uploadedfile_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
